#!/bin/bash

FILENAME="AUTHORS"
FULLNAME="$PROJECTDIR/$FILENAME"

# wait a little bit
$SLEEP $SLEEPSECONDS

if [ -f "$FULLNAME" ];
then
    print_ok
    res="0"
else
    print_ko
    res="1"
fi

# log results
log_results "none" "none" "$LOGFILE" "check if file AUTHORS exists" "$res"


