#!/bin/bash

# test if MANUAL file exists

FILENAME="man_1_simple_shell"
FULLNAME="$PROJECTDIR/$FILENAME"

# wait a little bit
$SLEEP $SLEEPSECONDS

if [ -f "$FULLNAME" ];
then
    print_ok
    res="0"
else
    print_ko
    res="1"
fi

