#!/bin/bash

# test if README file exists

FILENAME="README.md"
FULLNAME="$PROJECTDIR/$FILENAME"

# wait a little bit
$SLEEP $SLEEPSECONDS

if [ -f "$FULLNAME" ];
then
    print_ok
    res="0"
else
    print_ko
    res="1"
fi


