#!/bin/bash
#
# test with incorrect argument - test exit status

# command to execute
command="ls bad_arg"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# send commands
echo "$command" | $SHELL >> $OUTPUTFILE 2> $OUTPUTFILE
received_exit_status=`echo $?`
echo >> $OUTPUTFILE
echo "Exit status: " >> $OUTPUTFILE
echo $received_exit_status >> $OUTPUTFILE 

echo "$command" | $OSHELL >> $tmp_file 2> $tmp_file
expected_exit_status=`echo $?`
echo >> $tmp_file
echo "Exit status: " >> $tmp_file
echo $expected_exit_status >> $tmp_file 

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
if [ $received_exit_status -eq $expected_exit_status ]; then
    print_ok
    res="0"
  else
    print_ko
    res="1"
fi

# LOG RESULTS
log_results "$tmp_file" "$OUTPUTFILE" "$LOGFILE" "$command" "$res"

# clean up
stop_shell
rm -f $tmp_file
