#!/bin/bash
#
# run ls with arguments

tmp_file=".checker_tmp_file_$RANDOM"
tmp_filedir="/tmp"
tmp_filepath="$tmp_filedir/$tmp_file"
command="/bin/ls -la $tmp_filedir/"

# clean up
stop_shell
rm -f $tmp_filepath

# create a pseudo random file
touch $tmp_filepath
chmod 761 $tmp_filepath
# send commands
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &
echo "$command" | $OSHELL > $tmp_file 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat "$OUTPUTFILE" | grep "$tmp_file" | grep -c "rwxrw---x"`
if [ $nmatch -eq 1 ]; then
    print_ok
    res="0"
  else
    print_ko
    res="1"
fi

# LOG RESULTS
log_results "$tmp_file" "$OUTPUTFILE" "$LOGFILE" "$command" "$res"



# clean up
stop_shell
rm -f $tmp_file
