#!/bin/bash
#
# Empty the PATH and check if /bin/ls still works

command="/bin/ls"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# empty PATH
OLDPATH="$PATH"
PATH=""
# send commands
$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &
$ECHO "$command" | $OSHELL > $tmp_file 2> /dev/null &

# put PATH back
PATH="$OLDPATH"

# wait a little bit
$SLEEP $SLEEPSECONDS

cat $ERROROUTPUTFILE

# check the result
nmatch=`$CAT $OUTPUTFILE | $GREP -c "$tmp_file"`
if [ $nmatch -eq 1 ]; then
      print_ok
    res="0"
  else
    print_ko
    res="1"
fi

# LOG RESULTS
log_results "$tmp_file" "$OUTPUTFILE" "$LOGFILE" "$command" "$res"



# clean up
stop_shell
rm -f $tmp_file
